"""
main.py — FastAPI Application Entry Point
==========================================

This is the root of the entire backend application.

What it does:
  1. Loads environment variables from the .env file (ANTHROPIC_API_KEY lives here).
  2. Creates the FastAPI application instance with metadata (used in Swagger docs).
  3. Adds CORS middleware so this API can be called from any browser/client.
  4. Registers the webhook router under the /webhook URL prefix.
  5. Exposes a simple GET / health check endpoint so we can verify the server is alive.

How to run:
  python -m uvicorn src.main:app --reload

Interactive API docs (auto-generated by FastAPI):
  http://localhost:8000/docs
"""

# Load .env file FIRST — before anything else imports os.getenv.
# This ensures ANTHROPIC_API_KEY is available when ai_service.py loads.
from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from src.routes.webhook import router as webhook_router


# ─────────────────────────────────────────────────────────────
# Create the FastAPI app
# ─────────────────────────────────────────────────────────────
# title, description, version appear in the Swagger UI at /docs
app = FastAPI(
    title="Nistula Guest Message Handler",
    description=(
        "AI-powered guest messaging system for the Nistula hospitality platform. "
        "Receives raw guest messages via webhook, classifies them, drafts an AI reply "
        "using Claude, and returns a confidence score + recommended action."
    ),
    version="1.0.0",
)


# ─────────────────────────────────────────────────────────────
# CORS Middleware
# ─────────────────────────────────────────────────────────────
# Cross-Origin Resource Sharing (CORS) allows this API to accept
# requests from any origin (browser, Postman, frontend apps, etc.).
# In a real production environment, replace allow_origins=["*"]
# with the specific domain(s) of your frontend app.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # Allow all origins (open for assessment purposes)
    allow_methods=["*"],        # Allow all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],        # Allow all request headers
)


# ─────────────────────────────────────────────────────────────
# Register Routers
# ─────────────────────────────────────────────────────────────
# This mounts all routes defined in webhook.py under /webhook.
# So /message in webhook.py becomes /webhook/message here.
app.include_router(webhook_router, prefix="/webhook", tags=["Webhook"])


# ─────────────────────────────────────────────────────────────
# Health Check Endpoint
# ─────────────────────────────────────────────────────────────
# A simple GET / endpoint to confirm the server is running.
# Useful for monitoring tools, load balancers, and quick sanity checks.
@app.get("/", tags=["Health"])
def health_check():
    """Returns a simple status response to confirm the API is live."""
    return {"status": "ok", "service": "Nistula Guest Message Handler"}
